<!DOCTYPE html>                                                                                                                                                                                                                                 
<html>                                                                                                                                                                                                                                  

<head>                                                                                                                                                                                                                                  
    <title>Geocommsa-Celular</title>                                                                                                                                                                                                                                    
    <meta name="viewport" content="width=device-width, initial-scale=1">                                                                                                                                                                                                                                    
    <meta charset="utf-8">                                                                                                                                                                                                                                  
    <meta name="Geocommsa" content="" />                                                                                                                                                                                                                                    

    <script>                                                                                                                                                                                                                                    
        addEventListener("load", function() {                                                                                                                                                                                                                                   
            setTimeout(hideURLbar, 0);                                                                                                                                                                                                                                  
        }, false);                                                                                                                                                                                                                                  

        function hideURLbar() {                                                                                                                                                                                                                                 
            window.scrollTo(0, 1);                                                                                                                                                                                                                                  
        }                                                                                                                                                                                                                                   
    </script>                                                                                                                                                                                                                                   
    <link href="css/bootstrap.css" rel='stylesheet' type='text/css' />                                                                                                                                                                                                                                  
    <link href="css/simpleLightbox.css" rel='stylesheet' type='text/css' />                                                                                                                                                                                                                                 
    <link href="css/style.css" rel='stylesheet' type='text/css' />                                                                                                                                                                                                                                  
    <link href="css/fontawesome-all.css" rel="stylesheet">                                                                                                                                                                                                                                  

</head>                                                                                                                                                                                                                                 

<body>                                                                                                                                                                                                                                  
    <header>                                                                                                                                                                                                                                    
    <?php include 'header.html'; ?>                                                                                                                                                                                                                                 
    </header>                                                                                                                                                                                                                                   
    <!--//header-->                                                                                                                                                                                                                                 
    <div class="banner-inner-pesados">                                                                                                                                                                                                                              

    </div>                                                                                                                                                                                                                                  
    <ol class="breadcrumb">                                                                                                                                                                                                                                 
        <li class="breadcrumb-item">                                                                                                                                                                                                                                    
            <a href="index.php">Inicio</a>                                                                                                                                                                                                                                  
        </li>                                                                                                                                                                                                                                   
        <li class="breadcrumb-item active">Equipo Pesado</li>                                                                                                                                                                                                                               
        <li class="breadcrumb-item">                                                                                                                                                                                                                                    
                <a href="">Minería</a>                                                                                                                                                                                                                              
            </li>                                                                                                                                                                                                                                   
            <li class="breadcrumb-item">                                                                                                                                                                                                                                    
                    <a href="">Perforación</a>                                                                                                                                                                                                                                  
                </li>                                                                                                                                                                                                                                   
    </ol>                                                                                                                                                                                                                                   
    <!-- //banner-->                                                                                                                                                                                                                            

	<section class="banner-bottom">                                                                                                                                                                                                                                 
                   <div class="container">                                                                                                                                                                                                                         
                    <h3 class="tittle">Equipo Pesado</h3>                                                                                                                                                                                                                               
<br>                                                                                                                                                                                                                            
                    <div class="row inner-sec-wthree">                                                                                                                                                                                                                                                                                                                                                                          
            <div class="col-lg-6 bt-bottom-info" data-aos="fade-right">                                                                                                                                                                                                                                                                                                                                                                         

                <h4 style="color:#ff6a00">Seguimiento y monitoreo de Maquinaria y equipos pesados y telemática</h4>                                                                                                                                                                                                                                 

            </div>                                                                                                                                                                                                                                                                                                                                                                          
            <div class="col-lg-6 bt-bottom-info" data-aos="fade-left">                                                                                                                                                                                                                                                                                                                                                                          
                <div class="style-grid-2-text_info" data-aos="fade-left">                                                                                                                                                                                                                           
                <p><b>GEOCOMMSA permite realizar el seguimiento, gestione y controle las flotas de equipos pesados de construcción,                                                                                                                                                                                                                             
                            minería, agricultura, marítimo y servicios a la medida de las necesidades de nuestros clientes en lo referente al IiOT y Telemetria.                                                                                                                                                                                                                            
                        </b></p>                                                                                                                                                                                                                            
                        <p>GEOCOMMSA  desarrollo un dispositivo de control y seguimiento de equipos de construcción, de modo celular o dual y vía radio frecuencia                                                                                                                                                                                                                              
                            altamente resistente, lo que permite contar con registros oportunos de la operación diaria de los activos y equipos,                                                                                                                                                                                                                            
                            y con ello una mayor eficiencia de los equipos, facilitando la obtención a datos y analíticas en tiempo real.</p>                                                                                                                                                                                                                                                                                                                                                   

            </div>                                                                                                                                                                                                                          
    </div>                                                                                                                                                                                                                              
    </div>
        </section>                                                                                                                                                                                                                              
        <section class="grids_sec_2">                                                                                                                                                                                                                                                                                                                                                                           

        <div class="row style-grids_main">                                                                                                                                                                                                                                                                                                                                                                          
            <div class="col-md-6 grid_sec_info" data-aos="fade-right">                                                                                                                                                                                                                                                                                                                                                                          
                <div class="style-grid-2-text_info" data-aos="fade-right">                                                                                                                                                                                                                                                                                                                                                                          


                    <p>GEOCOMMSA desarrollo un dispositivo que  proporciona información oportuna sobre el estado y la posición de los equipos,                                                                                                                                                                                                                          
                        junto con registros operativos clave para que los responsables del mantenimiento y seguimiento de la productividad de los equipos,                                                                                                                                                                                                                          
                        permitiendo a los usuarios, puedan gestionar de forma oportuna su flota de construcción en las áreas más remotas.</p>                                                                                                                                                                                                                           

                        <p>Al obtener registros importantes de los parámetros de operación y productividad de los activos y de los diferentes equipos,                                                                                                                                                                                                                          
                            se aprovecha al máximo dichos registros, los cuales son valiosos informes de utilización y programacion de los mantenimiento de los equipos pesados,                                                                                                                                                                                                                            

                            Permitiendo a los clientes  saber dónde se encuentran sus equipos, si son productivos, si necesitan mantenimiento, o si son operados dentro de sus límites y si se están utilizando con eficiencia.</p>                                                                                                                                                                                                                         

                   <p>GEOCOMMSA desarrollo esta potente herramienta que permite una solución integral de telemática que incluye registros y parámetros que pueden ser configurados a las necesidades del cliente.</p>                                                                                                                                                                                                                           
                     </div>                                                                                                                                                                                                                                                                                                                                                                         
            </div>                                                                                                                                                                                                                                                                                                                                                                          
            <div class="col-md-6 style-image-Pesados" data-aos="fade-left">                                                                                                                                                                                                                                                                                                                                                                         
            </div>                                                                                                                                                                                                                                                                                                                                                                          






        </div>                                                                                                                                                                                                                                                                                                                                                              


    </section>                                                                                                                                                                                                                              

    <!--footer-->                                                                                                                                                                                                                                   
    <?php include 'footer.html'; ?>                                                                                                                                                                                                                                 

    <!-- js -->                                                                                                                                                                                                                                 
    <script src="js/jquery-2.2.3.min.js"></script>                                                                                                                                                                                                                                  
    <!-- //js -->                                                                                                                                                                                                                                   
    <!-- simpleLightbox -->                                                                                                                                                                                                                                 
	<script src="js/simpleLightbox.js"></script>                                                                                                                                                                                                                                    
	<script>                                                                                                                                                                                                                                    
		$('.proj_gallery_grid a').simpleLightbox();                                                                                                                                                                                                                                 
	</script>                                                                                                                                                                                                                                   
	<!-- //simpleLightbox -->                                                                                                                                                                                                                                   
    <!-- /js files -->                                                                                                                                                                                                                                  
	<link href='css/aos.css' rel='stylesheet prefetch' type="text/css" media="all" />                                                                                                                                                                                                                                   
	<link href='css/aos-animation.css' rel='stylesheet prefetch' type="text/css" media="all" />                                                                                                                                                                                                                                 
	<script src='js/aos.js'></script>                                                                                                                                                                                                                                   
	<script src="js/aosindex.js"></script>                                                                                                                                                                                                                                  
	<!-- //js files -->                                                                                                                                                                                                                                 
    <!-- start-smoth-scrolling -->                                                                                                                                                                                                                                  
    <script src="js/move-top.js"></script>                                                                                                                                                                                                                                  
    <script src="js/easing.js"></script>                                                                                                                                                                                                                                    
    <script>                                                                                                                                                                                                                                    
        jQuery(document).ready(function($) {                                                                                                                                                                                                                                    
            $(".scroll").click(function(event) {                                                                                                                                                                                                                                    
                event.preventDefault();                                                                                                                                                                                                                                 
                $('html,body').animate({                                                                                                                                                                                                                                    
                    scrollTop: $(this.hash).offset().top                                                                                                                                                                                                                                    
                }, 900);                                                                                                                                                                                                                                    
            });                                                                                                                                                                                                                                 
        });                                                                                                                                                                                                                                 
    </script>                                                                                                                                                                                                                                   

     <!-- /js -->                                                                                                                                                                                                                                   
       <script src="js/bootstrap.js"></script>                                                                                                                                                                                                                                  
    <!-- //js -->                                                                                                                                                                                                                                   
</body>                                                                                                                                                                                                                                 

</html>                                                                                                                                                                                                                                 